### ISSUE TITLE
Numbers not recognized

### ISSUE THREAD

**Issue by gkf01** [golastmile/rasa_nlu#214] opened 2017-03-15 13:20 UTC
rasa NLU version: 0.7.0a7

Used backend: spacy_sklearn & platform: osx

Issue: Numbers are not recognized. Rasa knows the start and end of the number in the input string but fails to recognize the number itself ("0" is inserted in the value "field")

**Comment by gkf01** [comment] 2017-03-15 13:25
Also, after examining the index.json file that is created inside the server model file after training, I realized that the numbers are being matched to wrong values.

**Comment by tmbo** [comment] 2017-03-15 16:22
@gkf01 thanks for your report, can you provide me with an example, e.g. query & training data?

**Comment by gkf01** [comment] 2017-03-23 10:58
Training data:
{
      "text": "$10",
      "entities": [
        {
          "entity": "number",
          "value": "10",
          "start": 1,
          "end": 3
        },
        {
          "entity": "currency",
          "value": "usd",
          "start": 0,
          "end": 1
        }
      ]
    }

Query: localhost:5000/parse?q=$10

Result:
[
  {
    "_text": "$10",
    "confidence": 0.79821972988268408,
    "entities": {
      "currency": {
        "confidence": null,
        "end": 1,
        "start": 0,
        "type": "value",
        "value": "usd"
      },
      "number": {
        "confidence": null,
        "end": 3,
        "start": 1,
        "type": "value",
        "value": ""
      }
    },
    "intent": "None"
  }
]

**Comment by tmbo** [comment] 2017-03-23 12:26
I am unable to reproduce this with the current master. Your example query results in:
```
{
"entities": [
{
"end": 1,
"entity": "currency",
"start": 0,
"value": "usd"
},
{
"end": 3,
"entity": "number",
"start": 1,
"value": "10"
}
],
"intent": {
"confidence": 0.5431373286771147,
"name": "restaurant_search"
},
"intent_ranking": [
{
"confidence": 0.5431373286771147,
"name": "restaurant_search"
},
{
"confidence": 0.284799038989382,
"name": "affirm"
},
{
"confidence": 0.12479809138102393,
"name": "goodbye"
},
{
"confidence": 0.04726554095247897,
"name": "greet"
}
],
"text": "$10"
}
```

**Comment by tmbo** [comment] 2017-03-31 11:36
I'll close this for now, let me know if this is still an issue for you.

**Comment by gkf01** [comment] 2017-04-10 12:43
Here are some sample output (don't worry about the intent since the training data is not adequate):

localhost:5000/parse?q=100
{
    "_text": "100",
    "confidence": 0.77723577885645512,
    "entities": {},
    "intent": "\"greeting\""
  }

localhost:5000/parse?q=4
{
    "_text": "4",
    "confidence": 0.74282103847887981,
    "entities": {
      "number": {
        "confidence": null,
        "end": 1,
        "start": 0,
        "type": "value",
        "value": "4"
      }
    },
    "intent": "\"greeting\""
  }

Similar results are obtained if I do not emulate wit.

The training data are here: [test.json.zip](https://github.com/golastmile/rasa_nlu/files/910049/test.json.zip)

**Comment by tmbo** [comment] 2017-04-10 14:24
I am not sure if you want to describe a bug. The above output does seem fine (although the entity is not detected in the first example, that is expected as the trained model most likely doesn't have a 100% accuracy). 

One thing you can try is experiment with the duckling integration in the latest master.

**Comment by gkf01** [comment] 2017-04-10 14:36
check this out:

{
    "_text": "1",
    "confidence": 0.79445430988573484,
    "entities": {
      "number": {
        "confidence": null,
        "end": 1,
        "start": 0,
        "type": "value",
        "value": ""
      }
    },
    "intent": "\"greeting\""
  }

{
    "_text": "12",
    "confidence": 0.75780290743962631,
    "entities": {
      "number": {
        "confidence": null,
        "end": 2,
        "start": 0,
        "type": "value",
        "value": ""
      }
    },
    "intent": "\"greeting\""
  }

{
    "_text": "100",
    "confidence": 0.77723395098749681,
    "entities": {
      "number": {
        "confidence": null,
        "end": 3,
        "start": 0,
        "type": "value",
        "value": "0"
      }
    },
    "intent": "\"greeting\""
  }

**Note that 509 is not present in the training data**
{
    "_text": "509",
    "confidence": 0.92630325353091258,
    "entities": {
      "number": {
        "confidence": null,
        "end": 3,
        "start": 0,
        "type": "value",
        "value": "509"
      }
    },
    "intent": "\"greeting\""
  }

Only the numbers that are included in the training data are not correctly recognized

**Comment by tmbo** [comment] 2017-04-10 14:36
Alright, that looks strange. I'll have a look at that.

**Comment by tmbo** [comment] 2017-04-10 15:14
If you look at the example data in the repository for wit https://github.com/golastmile/rasa_nlu/blob/master/data/examples/wit/demo-flights.json you can see that the entity values are wrapped in additional `"`, e.g. 
```
"entities" : [
        {
          "entity" : "location",
          "value" : "\"berlin\"",
          "role" : "from",
          "start" : 18,
          "end" : 24
        }]
```
looking at your data, these characters are not present. Did you download your data directly from wit.ai?

**Comment by tmbo** [comment] 2017-04-10 15:21
We are stripping these chars away, so this results in an error if they are not present. I just changed the stripping, so this won't be an issue with the current master anymore.

**Closed by tmbo** 2017-04-10 15:21 UTC
Labels: bug, irreproducible
