### ISSUE TITLE
training gets stuck

### ISSUE THREAD

**Issue by NagarajGond** [golastmile/rasa_nlu#160] opened 2017-02-15 05:05 UTC
#I have been trying rasa nlu. I have observed that if intent is more than 6 then training gets stuck.
I'm not sure how to debug this issue.

 python -m rasa_nlu.train -c config.json
Training to recognize 8 categories: 'greet', 'affirm', 'goodbye', 'test_config', 'test_issue', 'test_level', 'test_action', 'test_status'
Train classifier
extracting text features
now do training
num training samples: 32
...........

rasa-nlu==0.5.0.0
mitie==0.2.0

**Comment by amn41** [comment] 2017-02-15 13:13
It could just be taking a long time to train. We're working on the `mitie_sklearn` backend as a workaround to this.

**Comment by NagarajGond** [comment] 2017-02-16 04:16
After 3-4 hrs training gets terminated.

I will try with spacy_sklearn backend and share the result.

**Comment by amn41** [comment] 2017-02-16 08:13
you might be running out of memory

**Comment by Shravan40** [comment] 2017-02-16 08:54
Hey @amn41 

I too facing the same issue 

```
Training to recognize 1 categories: 'parseSms'
Train classifier
extracting text features
now do training
num training samples: 120
C: 200   f-score: 1
C: 400   f-score: 1
C: 300   f-score: 1
C: 100   f-score: 1
C: 0.01   f-score: 1
C: 50.005   f-score: 1
C: 25.0075   f-score: 1
C: 12.5088   f-score: 1
C: 6.25938   f-score: 1
C: 3.13469   f-score: 1
C: 1.57234   f-score: 1
C: 0.791172   f-score: 1
C: 0.400586   f-score: 1
best C: 0.791172
test on train: 
120 

overall accuracy: 1
Training time: 0 seconds.
df.number_of_classes(): 1

Training to recognize 19 labels: {name of individual labels comma seperated}
Part I: train segmenter
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
num threads: 4
cache size:  5
max iterations: 2000
loss per missed segment:  3
C: 20   loss: 3 	0.953586
C: 35   loss: 3 	0.953586
C: 20   loss: 4.5 	0.954993
C: 5   loss: 3 	0.953586
C: 20   loss: 1.5 	0.938115
C: 20   loss: 3.9 	0.953586
C: 20   loss: 4.8 	0.954993
C: 20   loss: 4.65 	0.954993
C: 20.7071   loss: 4.57071 	0.954993
C: 19.0461   loss: 4.53001 	0.954993
best C: 20
best loss: 4.5
num feats in chunker model: 4095
train: precision, recall, f1-score: 0.995787 0.997187 0.996486 
Part I: elapsed time: 113 seconds.

Part II: train segment classifier
now do training
num training samples: 714
// And it stuck here. 
```
![htop_details](https://cloud.githubusercontent.com/assets/1205111/23013948/e5bf73ee-f452-11e6-9524-5344454b4d62.png)

And output of `ps -eo pid,etime` say thats the process id number `11577` is running since `11360    18:30:02` and it doesn't even say, when it's going to end. 

If you can suggest me that what could be the optimal memory size for training of this data, then i can run it on cloud(ec2 instance). If and only if that newly created directory by this process can be copied and used on other machine.

**Comment by NagarajGond** [comment] 2017-02-16 12:21
yeah it would very helpful if you share the footprint of rasa nlu server and rasa nlu train engines.

**Comment by nmstoker** [comment] 2017-02-21 20:41
Are there any methods to increase the logging that is done when training?

It has rapidly become challenging to find out what's actually happening and where the issue is, and without insight it's difficult to determine the best way forward.  I had it going reasonably well (if a little slow, ie 4 hrs training on my laptop) until recently, but having added a number of extra training samples I think it's pushing it over some limit... I've twice left it training for a significant time (1st run 30+ hrs, and ~24 hrs 2nd run).

There's no obvious way to tell if it has crashed, but in my recent cases it has been stuck at the `num training samples: xxx` stage. Previously it would be getting further and then sit for ages on each of the stages.

My laptop has an i7 w/ 8Gb. It does seem to be using up the majority of the physical memory but I'm not sure if it actually ran out or just got close to the limit.

**Comment by amn41** [comment] 2017-02-22 10:07
Understood. Now that it's merged in - could you please try the `mitie_sklearn` backend & see if that solves these issues?

**Comment by nmstoker** [comment] 2017-02-23 22:25
I tried with `mitie_sklearn` last night (I stumbled slightly on setting it up, my own fault, but appeared to figure it out eventually).  The initial training period went more quickly than the previous two nights' runs, but once it got onto Part II it then seemed to hang.  I left it overnight till this morning, thinking it could just be slow and it seemed to be working when I left for work.  However I've just got back from the office and find that it has died (precisely when I don't know, but after 9am and before 10pm!).  There's a message Killed, which I assume may come from the code (or perhaps it's from the OS?)

This morning I did briefly check the RAM - it had ~200Mb free of the 8Gb which isn't a lot, but I recall it using up a lot on previous attempts.

Any suggestions on things I could check or do?

Incidentally if all goes to plan, I will be getting a new laptop w/ 16Gb RAM mid-next week, so would be able to set it up the same basic way and will then see if that makes a difference.

![roybottrainingcrash](https://cloud.githubusercontent.com/assets/3694484/23281747/7ec4df66-fa16-11e6-8aa3-b450a62a4fc0.png)

**Comment by Shravan40** [comment] 2017-02-27 07:13
I tried training my model using `mitie_sklearn` with updated version. And it got terminated after running for more than 24 hours. 

```
Training to recognize 2 categories: 'parseSms', 'smsParse'
Train classifier
extracting text features
now do training
num training samples: 144
C: 200   f-score: 0.965278
C: 400   f-score: 0.965278
C: 300   f-score: 0.965278
C: 100   f-score: 0.965278
C: 0.01   f-score: 0.972222
C: 50.005   f-score: 0.965278
C: 25.0075   f-score: 0.965278
C: 12.5088   f-score: 0.965278
C: 6.25938   f-score: 0.965278
C: 3.13469   f-score: 0.965278
C: 1.57234   f-score: 0.965278
C: 0.791172   f-score: 0.965278
C: 0.400586   f-score: 0.965278
best C: 0.01
test on train: 
140   0 
  4   0 

overall accuracy: 0.972222
Training time: 18 seconds.
df.number_of_classes(): 2

Training to recognize 20 labels: 'name of each labels'
Part I: train segmenter
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
num threads: 4
cache size:  5
max iterations: 2000
loss per missed segment:  3
C: 20   loss: 3 	0.920746
C: 35   loss: 3 	0.926573
C: 20   loss: 4.5 	0.923077
C: 5   loss: 3 	0.920746
C: 20   loss: 1.5 	0.91958
C: 49.8733   loss: 3.19453 	0.918415
C: 35.2337   loss: 2.25036 	0.91958
C: 35.1825   loss: 3.21135 	0.920746
C: 34.4146   loss: 2.74308 	0.923077
C: 33.5173   loss: 3.0227 	0.923077
C: 36.7775   loss: 2.94033 	0.923077
C: 35.0349   loss: 2.94862 	0.91958
best C: 35
best loss: 3
num feats in chunker model: 4095
train: precision, recall, f1-score: 0.967232 0.997669 0.982215 
Part I: elapsed time: 174 seconds.

Part II: train segment classifier
now do training
num training samples: 887
C: 200   f-score: 0.972808
C: 400   f-score: 0.972808
C: 300   f-score: 0.972808
C: 100   f-score: 0.972808
C: 0.01   f-score: 0.871549
C: 600   f-score: 0.972808
C: 1400   f-score: 0.972808
C: 3000   f-score: 0.972808
C: 5000   f-score: 0.972808
C: 2550   f-score: 0.972808
C: 1325   f-score: 0.972808
C: 712.5   f-score: 0.972808
C: 406.25   f-score: 0.972808
C: 253.125   f-score: 0.972808
C: 176.562   f-score: 0.972808
C: 138.281   f-score: 0.972808
C: 119.141   f-score: 0.972808
C: 109.57   f-score: 0.972808
C: 104.785   f-score: 0.972808
C: 102.393   f-score: 0.972808
C: 101.196   f-score: 0.972808
C: 100.598   f-score: 0.972808
C: 100.299   f-score: 0.972808
best C: 100.598
python: src/mitie.cpp:87: const T& {anonymous}::checked_cast(const void*) [with T = mitie::named_entity_extractor]: Assertion `ptr' failed.
[1]    15560 abort      python -m rasa_nlu.train -c config.json
```

**Comment by nmstoker** [comment] 2017-03-03 00:12
Quick update: I've found that with the new 16Gb laptop, my previous problems have gone and it can complete training.  I've now got other issues, but that's a separate thing! :smile:

**Closed** 2017-03-10 10:40 UTC
Labels: question

**Comment by ksivaganesh99** [comment] 2017-05-24 05:48
Hi,,, This issue still persists, this might be considered to reopen. when we have 100 odd utterances to be trained, the NLU kills after trying to train for long. Would some be fix available in near future for this??? or is there any workaround. I am using 7 GB RAM Linux Server

C: 18.4799   loss: 4.43564      0.725
C: 19.1528   loss: 4.55312      0.725
best C: 20
best loss: 4.5
num feats in chunker model: 4095
train: precision, recall, f1-score:    0.975 0.962963 0.968944
Part I: elapsed time: 37 seconds.

Part II: train segment classifier
now do training
num training samples: 83
C: 200   f-score: 0.940722
C: 400   f-score: 0.940722
C: 300   f-score: 0.940722
C: 100   f-score: 0.940722
C: 0.01   f-score: 0.902062
C: 600   f-score: 0.940722
C: 1400   f-score: 0.940722
C: 3000   f-score: 0.940722
C: 5000   f-score: 0.940722
C: 2550   f-score: 0.940722
C: 1325   f-score: 0.940722
C: 712.5   f-score: 0.940722
C: 406.25   f-score: 0.940722
C: 253.125   f-score: 0.940722
C: 176.562   f-score: 0.940722
C: 138.281   f-score: 0.940722
C: 119.141   f-score: 0.940722
C: 109.57   f-score: 0.940722
C: 104.785   f-score: 0.940722
C: 102.393   f-score: 0.940722
C: 101.196   f-score: 0.940722
C: 100.598   f-score: 0.940722
C: 100.299   f-score: 0.940722
best C: 100.598

**Comment by tmbo** [comment] 2017-05-24 06:07
The workaround is to avoid the mittie classifier. There isn't much we can do about this as this is more of an issue of the underlying MITIE library.

**Comment by gagan-bansal** [comment] 2017-08-24 09:47
Please read detailed explanation about [MITIE working](https://github.com/mit-nlp/MITIE/issues/11#issuecomment-76982370). That may solve the long duration training problem.

**Comment by vinodindia** [comment] 2019-06-25 11:47
try breaking down your large trainingset into small trainingsets and give that folder path(where broken down trainignsets are present) to the RASA nlu like
"python -m rasa train nlu -c config.yml --out models -u data\NCDomainData"
where NCDomainData folder contains the broken down datasets
